# Data Cleaning
**Phase 1: Counting**  
Objective: Quantify the "noise" and structure of the raw text.

[x] `emoji_count`: Create a new column to store the count of emojis per comment (using Unicode regex).

[x] `punct_count`: Create a new column to count standard punctuation (., ,, !, ?, ;, :) to evaluate sentence structure and readability.

**Phase 2: Lighter Cleaning (LLM-Ready)**  
Objective: Prepare text for sentiment analysis while preserving context.

[x] Light text retains Unicode emojis, punctuation, capitalization and stopwords. Normalization expands contractions and removes URLs.

[x] Context Preservation: Retain original punctuation and stopwords, as these are critical for maintaining the nuance and "voice" of the community.

**Phase 3: Heavier Cleaning (NLP-Ready)**  
Objective: Normalize data for traditional linguistic and statistical modeling.

[x] Tokenization & Normalization: Strip non-alphanumeric characters.

[x] Stopword Removal: Filter out high-frequency, low-value words (e.g., "the", "and", "is").

[x] Lowercasing: Standardize all text to improve word frequency accuracy.

**Phase 4: Targeted Windowing**  
[x] Use the Season 8 islander alias map and entrance metadata.

[x] Attention windows: seven retained words on each side from `body_clean_heavy`; save as `islander_windows` for 04.

[x] Sentiment windows: fifteen words on each side from `body_clean_light`; preserve original `window_text` and masked `model_text`; save as `islander_sentiment_windows` for 05.

[x] Both branches restrict to study-period comments and episodes at or after entrance. Multiple mentions remain separate windows.

**Shortcomings**  
I will NOT be looking at the essence of replies. That is, maybe there could be a comment that created more polarized debate. I do not wish to do this.

## Setup

### Libraries

In [99]:
import duckdb
import pandas as pd

import re
import contractions
import emoji
import html
import ftfy

### Stopwords

In [100]:
import nltk
from nltk.corpus import stopwords

# Download standard list of English stopwords
nltk.download('stopwords')

# 1. Start with standard NLTK
custom_stopwords = set(stopwords.words('english'))

# 2. Add your Reddit/Internet-specific "filler"
# These are words that appear constantly but carry no sentiment value 
# regarding the Islanders themselves.
internet_fillers = {
    'lol', 'lmao', 'lmfao', 'fr', 'rn', 'ig', 'idk', 'im', 'u', 'ur', 
    'n', 'gon', 'wanna', 'gonna', 'literally', 'actually', 'totally',
    'just', 'like', 'really', 'would', 'could', 'think', 'say', 'know'
}

# 3. Combine them
all_stopwords = custom_stopwords.union(internet_fillers)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/edieespejo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

We need to double-check that we are in the right folder.

In [101]:
import os
# Print the current working directory so you know where you are
print("Current folder:", os.getcwd())

# List all files in the directory one level up to find where your DB really is
import os
print("Files in parent folder:", os.listdir("../data/"))

Current folder: /Users/edieespejo/GitHub/data-by-edie/004-love-island/notebooks
Files in parent folder: ['kalshi', 'LoveIslandUSA_S8_Misc', '.DS_Store', 'archive', 'LoveIslandUSA_S8_Manual', 'LoveIslandUSA_S8', 'LoveIslandUSA_S7', 'metadata', 'love_island_reddit.duckdb']

Let's see what's in our database.

In [102]:
con = duckdb.connect("../data/love_island_reddit.duckdb")

# This will print the actual table names to your screen
print(con.execute("SHOW TABLES").df())

con.close()

                             name
0                        comments
1  islander_sentiment_proportions
2      islander_sentiment_windows
3                islander_windows
4                     submissions
5                           users

### Helpers

In [103]:
# Emoji count helper
def get_emoji_count(text):
    if not isinstance(text, str): return 0
    return len([char for char in text if char in emoji.EMOJI_DATA])

# Punctuation count helper
def get_punct_count(text):
    if not isinstance(text, str): return 0
    return len(re.findall(r'[.,!?;:]', text))

# Light cleaning: just remove emojis
def light_clean(text):
    if not isinstance(text, str): return text
    return emoji.demojize(text)

# Text to string, handling None and NaN values
def safe_text(text):

    if text is None:
        return ""

    try:
        if pd.isna(text):
            return ""
    except Exception:
        pass

    return str(text)

# Remove URLs from text
def remove_urls(text):
    return re.sub(r"http\S+|www\S+", " ", text, flags=re.IGNORECASE)

# Normalize text: unescape HTML, fix text, expand contractions, remove URLs
def normalize_all(text):
    # This combines your normalization and safe_text
    text = safe_text(text)
    text = html.unescape(text)
    text = ftfy.fix_text(text)
    text = contractions.fix(text)
    text = remove_urls(text)
    return text

# Clean text lightly: normalize and remove extra whitespace
def clean_light(text):
    text = normalize_all(text)
    return re.sub(r"\s+", " ", text).strip()

# Clean text heavily: normalize, convert emojis to tags, and strip non-alphanumeric characters
def clean_heavy(text):
    text = normalize_all(text)
    text = emoji.demojize(text)
    # Convert emojis to tags
    text = re.sub(r":([a-zA-Z0-9_+-]+):", r" [emoji_\1] ", text)
    # Lowercase and remove non-alphanumerics
    text = re.sub(r"[^a-z0-9\s'\[\]_]", " ", text.lower())
    
    # Tokenize and remove stopwords
    words = text.split()
    filtered_words = [w for w in words if w not in all_stopwords]
    
    return " ".join(filtered_words).strip()

## Apply

In [104]:
# 1. Connect
con = duckdb.connect("../data/love_island_reddit.duckdb")

# 2. Add all columns at once
con.execute("""
    ALTER TABLE comments ADD COLUMN IF NOT EXISTS emoji_count INTEGER DEFAULT 0;
    ALTER TABLE comments ADD COLUMN IF NOT EXISTS punct_count INTEGER DEFAULT 0;
    ALTER TABLE comments ADD COLUMN IF NOT EXISTS body_clean_light TEXT;
    ALTER TABLE comments ADD COLUMN IF NOT EXISTS body_clean_heavy TEXT;
""")

# 3. Pull data
df = con.execute("SELECT id, body FROM comments").df()

# 4. Apply everything (using your modular utilities)
df['emoji_count'] = df['body'].apply(get_emoji_count)
df['punct_count'] = df['body'].apply(get_punct_count)
df['body_clean_light'] = df['body'].apply(clean_light)
df['body_clean_heavy'] = df['body'].apply(clean_heavy)

# 5. Push everything back to DuckDB
con.execute("CREATE OR REPLACE TEMP TABLE updates AS SELECT id, emoji_count, punct_count, body_clean_light, body_clean_heavy FROM df")

con.execute("""
    UPDATE comments 
    SET emoji_count = updates.emoji_count,
        punct_count = updates.punct_count,
        body_clean_light = updates.body_clean_light,
        body_clean_heavy = updates.body_clean_heavy
    FROM updates 
    WHERE comments.id = updates.id
""")

print("Transformation complete: Light, Heavy, and Metrics added.")
con.close()

Transformation complete: Light, Heavy, and Metrics added.

## Quality Control

In [105]:
con = duckdb.connect("../data/love_island_reddit.duckdb")

# 1. Descriptive stats for the new columns
summary = con.execute("""
    SELECT 
        COUNT(*) as total_comments,
        AVG(emoji_count) as avg_emojis,
        MAX(emoji_count) as max_emojis,
        AVG(punct_count) as avg_punct,
        MAX(punct_count) as max_punct,
        -- How many people don't use emojis/punct at all?
        SUM(CASE WHEN emoji_count = 0 THEN 1 ELSE 0 END) as zero_emoji_count,
        SUM(CASE WHEN punct_count = 0 THEN 1 ELSE 0 END) as zero_punct_count
    FROM comments
""").df()

print("--- Feature Summary Statistics ---")
print(summary.T) # .T transposes it so it's easier to read vertically

# 2. Distribution check (The "Is this normal?" check)
# See the top 10 most emoji-heavy comments
print("\n--- Top 10 Emoji-Heavy Comments ---")
print(con.execute("SELECT body, emoji_count FROM comments ORDER BY emoji_count DESC LIMIT 10").df())

con.close()

--- Feature Summary Statistics ---
                              0
total_comments    205306.000000
avg_emojis             0.272759
max_emojis            50.000000
avg_punct              1.441838
max_punct            126.000000
zero_emoji_count  172131.000000
zero_punct_count   97044.000000

--- Top 10 Emoji-Heavy Comments ---
                                                body  emoji_count
0  Seeing Jana in my commercials 😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍...           50
1  Caleb baby, you can have as much cake as you w...           34
2  Delicious… get that mean girl off my screen 🙌🏾...           34
3  LETS FUCKING GOOOOOOOOOOOOOOOOOOOOOO WE WONNNN...           31
4         Poor Caleb 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭           31
5                     😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭           30
6  Kayda!!!!!!!!!!!!  \n🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩...           30
7     You’ll be alright 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂           28
8  The girls not crying or reacting when Sol’s na...           25
9  “What the hell is yall type?”😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭...           23

In [106]:
import duckdb

con = duckdb.connect("../data/love_island_reddit.duckdb")

# Preview the raw, light, and heavy bodies
print("--- Top 3 Rows Inspection ---")
print(con.execute("SELECT body, body_clean_light, body_clean_heavy FROM comments LIMIT 3").df())

con.close()

--- Top 3 Rows Inspection ---
                                                body  \
0  ### **SORT** this Discussion &#x1F3A8;\n---\n-...
1  When Bryce bragged to the guys how kind and ni...
2  Loooved that! He is looking way past her beaut...

                                    body_clean_light  \
0  ### **SORT** this Discussion 🎨 --- - sort **by...
1  When Bryce bragged to the guys how kind and ni...
2  Loooved that! He is looking way past her beaut...

                                    body_clean_heavy
0  sort discussion [emoji_artist_palette] sort [b...
1  bryce bragged guys kind nice girl [emoji_loudl...
2  loooved looking way past beautiful looks truly...

Here, we verify whether we have cleaned up the data.

In [107]:
con = duckdb.connect("../data/love_island_reddit.duckdb")

# Calculate average length (in characters)
stats = con.execute("""
    SELECT 
        AVG(LENGTH(body)) as avg_raw_len,
        AVG(LENGTH(body_clean_light)) as avg_light_len,
        AVG(LENGTH(body_clean_heavy)) as avg_heavy_len
    FROM comments
""").df()

print("\n--- Average Character Length Comparison ---")
print(stats.T)

con.close()

--- Average Character Length Comparison ---
                       0
avg_raw_len    97.500500
avg_light_len  97.326498
avg_heavy_len  62.649280

I actually find no issue with this filter. If we have a `body_clean_heavy` that is too short, I wouldn't necessarily want to use that data anyway.

In [108]:
# Check for "Over-cleans"
# If a comment is now less than 10 characters, it might be purely emojis or empty.
con = duckdb.connect("../data/love_island_reddit.duckdb")

print("--- Potential Over-cleaned Comments ---")
print(con.execute("""
    SELECT body, body_clean_heavy 
    FROM comments 
    WHERE LENGTH(body_clean_heavy) < 10 
    LIMIT 10
""").df())

con.close()

--- Potential Over-cleaned Comments ---
            body body_clean_heavy
0        Deadass          deadass
1    Seriously.         seriously
2   Sincerely \*        sincerely
3       majority         majority
4       Reaaalll         reaaalll
5           Zach             zach
6  He gives ick         gives ick
7       Wait why             wait
8           Lmao
9     i cackled           cackled

## Study Period Only

In [109]:
con = duckdb.connect("../data/love_island_reddit.duckdb")

In [110]:
date_ranges = con.execute("""
SELECT
    'posts' AS dataset,
    MIN(created_utc) AS min_date,
    MAX(created_utc) AS max_date,
    COUNT(*) AS total_rows
FROM submissions

UNION ALL

SELECT
    'comments',
    MIN(created_utc),
    MAX(created_utc),
    COUNT(*)
FROM comments
""").df()

date_ranges

    dataset      min_date      max_date  total_rows
0     posts  1.780468e+09  1.783903e+09         157
1  comments  1.780506e+09  1.784162e+18      205306

In [111]:
date_ranges = con.execute("""
SELECT
    'posts' AS dataset,
    MIN(created_at) AS min_date,
    MAX(created_at) AS max_date,
    COUNT(*) AS total_rows
FROM submissions

UNION ALL

SELECT
    'comments',
    MIN(created_at),
    MAX(created_at),
    COUNT(*)
FROM comments
""").df()

date_ranges

    dataset            min_date            max_date  total_rows
0     posts 2026-06-02 23:31:20 2026-07-12 17:34:04         157
1  comments 2026-06-02 17:20:04 2026-07-15 17:36:52      205306

In [112]:
con.execute("""
ALTER TABLE comments
ADD COLUMN IF NOT EXISTS keep_analysis VARCHAR
""")

con.execute("""
UPDATE comments
SET keep_analysis = CASE
    WHEN created_at >= TIMESTAMP '2026-06-02 07:00:00'
     AND created_at <  TIMESTAMP '2026-07-13 07:00:00'
    THEN 'Y'
    ELSE 'N'
END
""")

In [113]:
con.execute("""
SELECT
    keep_analysis,
    COUNT(DISTINCT id) AS num_comments,
    MIN(created_at) AS min_date,
    MAX(created_at) AS max_date
FROM comments
GROUP BY keep_analysis
ORDER BY keep_analysis
""").df()

  keep_analysis  num_comments            min_date            max_date
0             N            89 2026-07-13 07:09:50 2026-07-15 17:36:52
1             Y        205217 2026-06-02 17:20:04 2026-07-13 06:59:53

In [114]:
con.close()

## Season and Episode

In [115]:
con = duckdb.connect("../data/love_island_reddit.duckdb")

In [116]:
submission_episode_preview = con.execute("""
SELECT
    id,
    title,
    CASE
        WHEN REGEXP_MATCHES(title, '(?i)finale')
            THEN 35
        ELSE TRY_CAST(
            REGEXP_EXTRACT(
                title,
                '(?i)episode[[:space:]]+([0-9]+)',
                1
            ) AS INTEGER
        )
    END AS episode
FROM submissions
ORDER BY episode NULLS LAST, title
""").df()

submission_episode_preview["season"] = 8

submission_episode_preview

,id,title,episode,season
0,1tvbdpi,Season 8 - Episode 1 - Cast Opinions Discussion,1,8
1,1tvbdoe,Season 8 - Episode 1 - Post Episode Discussion,1,8
2,1tvh1f9,Season 8 Episode 1: Post Show Thoughts and Fir...,1,8
3,1tv942p,[SPOILER] Season 8 - Episode 1 - Tuesday June ...,1,8
4,1tv9sql,[WITH Ads] Season 8 - Episode 1 - Tuesday June...,1,8
...,...,...,...,...
152,1uuyaa3,Season 8 - Finale - Post Episode Discussion,35,8
153,1uuwgwe,[NONSPOILER] Season 8 - Finale - Sunday July 1...,35,8
154,1uuw534,[SPOILER] Season 8 - Finale - Sunday July 12 -...,35,8
155,1uuwswc,[WITH Ads] Season 8 - Finale - Sunday July 12 ...,35,8
156,1uuwsvl,[WITHOUT Ads] Season 8 - Finale - Sunday July ...,35,8

In [117]:
submission_episode_preview[
    submission_episode_preview["title"].str.contains(
        "finale",
        case=False,
        na=False
    )
]

,id,title,episode,season
152,1uuyaa3,Season 8 - Finale - Post Episode Discussion,35,8
153,1uuwgwe,[NONSPOILER] Season 8 - Finale - Sunday July 1...,35,8
154,1uuw534,[SPOILER] Season 8 - Finale - Sunday July 12 -...,35,8
155,1uuwswc,[WITH Ads] Season 8 - Finale - Sunday July 12 ...,35,8
156,1uuwsvl,[WITHOUT Ads] Season 8 - Finale - Sunday July ...,35,8

In [118]:
# episode_counts = (
#     submission_episode_preview["episode"]
#     .value_counts(dropna=False)
#     .rename_axis("episode")
#     .reset_index(name="num_submissions")
#     .sort_values("episode", na_position="last")
#     .reset_index(drop=True)
# )

# episode_counts

In [119]:
con.register(
    "submission_episode_updates",
    submission_episode_preview
)

con.execute("""
ALTER TABLE submissions
ADD COLUMN IF NOT EXISTS episode INTEGER
""")

con.execute("""
ALTER TABLE submissions
ADD COLUMN IF NOT EXISTS season INTEGER
""")

con.execute("""
UPDATE submissions AS s
SET
    episode = u.episode,
    season = u.season
FROM submission_episode_updates AS u
WHERE s.id = u.id
""")

In [120]:
# con.execute("""
# SELECT
#     season,
#     episode,
#     COUNT(*) AS num_submissions
# FROM submissions
# GROUP BY season, episode
# ORDER BY season, episode NULLS LAST
# """).df()

In [121]:
con.execute("""
ALTER TABLE comments
ADD COLUMN IF NOT EXISTS episode INTEGER
""")

con.execute("""
ALTER TABLE comments
ADD COLUMN IF NOT EXISTS season INTEGER
""")

con.execute("""
UPDATE comments AS c
SET
    episode = s.episode,
    season = s.season
FROM submissions AS s
WHERE c.post_id = s.id
""")

In [122]:
# con.execute("""
# SELECT
#     season,
#     episode,
#     COUNT(DISTINCT id) AS num_comments
# FROM comments
# GROUP BY season, episode
# ORDER BY season, episode NULLS LAST
# """).df()

In [123]:
con.close()

## Cast

In [124]:
s7_islander_map = {
    "Ace Greene": ["ace"],
    "Amaya Espinal": ["amaya", "amaya papaya", "papaya"],
    "Andreina Santos": ["andreina", "andreena", "adriena"],
    "Austin Shepard": ["austin"],
    "Bryan Arenales": ["bryan", "brian"],
    "Charlie Georgiou": ["charlie"],
    "Chris Seeley": ["chris"],
    "Cierra Ortega": ["cierra", "ciara", "sierra", "ciarra"],
    "Clarke Carraway": ["clarke", "clark"],
    "Courtney Watson": ["coco", "courtney"],
    "Elan Bibas": ["elan", "elon"],
    "Gracyn Blackmore": ["gracyn", "gracelyn", "graceyn"],
    "Hannah Fields": ["hannah", "hana"],
    "Huda Mustafa": ["huda", "hudabubbaaa", "hurricane huda"],
    "Iris Kendall": ["iris"],
    "Isabelle-Anne Walker": ["belle-a", "bellea", "isabelle", "belle", "bella"],
    "JD Dodard": ["jd"],
    "Jaden Duggar": ["jaden", "jaiden"],
    "Jalen Brown": ["jalen"],
    "Jeremiah Brown": ["jeremiah", "jeramiah"],
    "Jose Garcia": ["pepe", "jose"],
    "Michelle Bissainthe": ["chelley", "michelle", "cheley"],
    "Nicolas Vansteenberghe": ["nic", "nicolas", "nick", "big belgian", "nicolandria"],
    "Olandria Carthen": ["olandria", "ola", "nicolandria"],
    "Savanna Einerson": ["vanna", "savanna", "savannah"],
    "Taylor Williams": ["taylor"],
    "Thomas Palma": ["tj", "thomas"],
    "Yulissa Escobar": ["yulissa"],
    "Zac Woodworth": ["zac"],
    "Zak Srakaew": ["zak"]
}

In [125]:
islander_map = {
    "Alannah Keyser": [
        "alannah",
        "alanna",
        "alana"
    ],

    "Amora Cacheé Robinson": [
        "amora",
        "amora cachee",
        "amora cachée"
    ],

    "Aniya Harvey": [
        "aniya",
        "ania",
        "aniyah"
    ],

    "Beatriz Hatz": [
        "beatriz",
        "bea",
        "beatrice"
    ],

    "Bryce Alakai Dettloff": [
        "bryce",
        "alakai"
    ],

    "Caleb McDaniel": [
        "caleb"
    ],

    "Carl Lee Schmidt": [
        "carl",
        "carl lee"
    ],

    "Chandlar Wilson": [
        "chandlar",
        "chandler"
    ],

    "Chaten Nehra": [
        "chay",
        "chaten"
    ],

    "Corbin Mims": [
        "corbin",
        "corby"
    ],

    "Corey Sawyer Jr.": [
        "corey",
        "cory"
    ],

    "Dylan Wrona": [
        "dylan"
    ],

    "Gabriel Vasconcelos": [
        "gabriel",
        "gabe",
        "gab"
    ],

    "Gal Tshnieder": [
        "gal"
    ],

    "Jaiden Bacciocco": [
        "jaiden",
        "jaden",
        "jayden"
    ],

    "Jennifer Terry": [
        "jen",
        "jenn",
        "jennifer"
    ],

    "Kayda Bosse": [
        "kayda",
        "kaida",
        "kayla"
    ],

    "Keyon Harry": [
        "keyon",
        "keyan",
        "keyyon"
    ],

    "Kuman Chandler": [
        "kc",
        "k.c.",
        "k c",
        "kuman"
    ],

    "Kyle Greene": [
        "kyle"
    ],

    "Mackenzie Annis": [
        "kenzie",
        "mackenzie",
        "mckenzie"
    ],

    "Melanie Moreno": [
        "melanie",
        "mel",
        "melany"
    ],

    "Parmida Keshani": [
        "parmida",
        "parmi",
        "parm",
        "parmesan"
    ],

    "Ronnie Gunter": [
        "ronnie",
        "ronny"
    ],

    "Ryan Ten Hulscher": [
        "ryan"
    ],

    "Sean Reifel": [
        "sean",
        "shawn"
    ],

    "Sherleaz Eugene": [
        "sydney",
        "syd",
        "sydnee",
        "sydnie",
        "sherleaz"
    ],

    "Sincere Rhea": [
        "sincere",
        "sin"
    ],

    "Sol Dean": [
        "sol"
    ],

    "Tierra Davis": [
        "tierra",
        "titi",
        "ti ti",
        "tiara"
    ],

    "Tino Ellis": [
        "tino"
    ],

    "Trae Taylor": [
        "trae",
        "trey",
        "tray"
    ],

    "Trinity Tatum": [
        "trinity",
        "trini",
        "trinnie"
    ],

    "Zacharias Georgiou": [
        "zach",
        "zack",
        "zac",
        "zacharias"
    ]
}

## Create Target Windows

In [126]:
islander_metadata = pd.read_csv('../data/metadata/islander_metadata.csv')
# islander_metadata

In [127]:
import duckdb
import re
import pandas as pd

# 1. Setup Master Pattern
all_names = []
for nicknames in islander_map.values():
    all_names.extend(nicknames)
all_names = sorted(list(set(all_names)), key=len, reverse=True)
name_pattern = re.compile(r'\b(' + '|'.join(map(re.escape, all_names)) + r')\b', re.IGNORECASE)

def get_word_windows(text, target_islander, window_size=10):
    words = text.split()
    # Pattern for this specific islander (canonical + nicknames)
    target_pattern = re.compile(r'\b(' + '|'.join(map(re.escape, islander_map[target_islander])) + r')\b', re.IGNORECASE)
    
    windows = []
    for i, word in enumerate(words):
        if target_pattern.match(word):
            start = max(0, i - window_size)
            end = min(len(words), i + window_size + 1)
            
            # Extract and anonymize
            window_words = words[start:end]
            clean_window = [name_pattern.sub("[ISLANDER]", w) for w in window_words]
            windows.append(" ".join(clean_window))
    return windows

# 2. Execution
con = duckdb.connect("../data/love_island_reddit.duckdb")
# df = con.execute("SELECT id, body_clean_heavy FROM comments").df()

df = con.execute("""
SELECT
    id,
    body_clean_heavy
FROM comments
WHERE keep_analysis = 'Y'
  AND body_clean_heavy IS NOT NULL
""").df()


# Build the Expanded DataFrame
all_rows = []
for _, row in df.iterrows():
    # Check mentions for every Islander in the map
    for islander in islander_map.keys():
        windows = get_word_windows(row['body_clean_heavy'], islander, window_size=7)
        for win in windows:
            all_rows.append({
                'comment_id': row['id'],
                'target_islander': islander,
                'window_text': win
            })

df_windows = pd.DataFrame(all_rows)

In [128]:
# Add episode to each window using comment_id
comment_episodes = con.execute("""
SELECT DISTINCT
    id AS comment_id,
    episode
FROM comments
""").df()

df_windows = (
    df_windows
    .merge(
        comment_episodes,
        on="comment_id",
        how="left",
        validate="many_to_one",
    )
)

In [129]:
df_windows = (
    df_windows
    .merge(
        islander_metadata[
            ["islander", "entrance_episode"]
        ],
        left_on="target_islander",
        right_on="islander",
        how="left",
        validate="many_to_one",
    )
    .drop(columns="islander")
)

In [130]:
unmatched_islanders = (
    df_windows.loc[
        df_windows["entrance_episode"].isna(),
        "target_islander",
    ]
    .drop_duplicates()
    .tolist()
)

print("Unmatched islanders:", unmatched_islanders)

Unmatched islanders: []

In [131]:
windows_before = len(df_windows)

df_windows = (
    df_windows[
        df_windows["episode"].notna()
        & df_windows["entrance_episode"].notna()
        & (
            df_windows["episode"]
            >= df_windows["entrance_episode"]
        )
    ]
    .reset_index(drop=True)
)

print(f"Removed {windows_before - len(df_windows):,} invalid windows.")

Removed 11,116 invalid windows.

In [132]:
# Store the final cleaned windows
con.execute("""
CREATE OR REPLACE TABLE islander_windows AS
SELECT *
FROM df_windows
""")

print(
    f"Stored {len(df_windows):,} windows "
    "across all cast members."
)

con.close()

Stored 244,351 windows across all cast members.

In [133]:
df_windows.head(10)

,comment_id,target_islander,window_text,episode,entrance_episode
0,oqrjrnv,Bryce Alakai Dettloff,[ISLANDER] bragged guys kind nice girl [emoji_...,7,1
1,oqrv3z0,Trinity Tatum,yeah enjoy interactions feel way [ISLANDER] ta...,7,1
2,oqrhf82,Bryce Alakai Dettloff,glad [ISLANDER] trin involved mess hope ages well,7,1
3,oqrkife,Gabriel Vasconcelos,[ISLANDER] gross wants fuck,7,3
4,oqrrs6p,Melanie Moreno,[ISLANDER] double dipping last episode offende...,7,1
5,oqrrs6p,Sincere Rhea,last episode offended people bad dreamed world...,7,1
6,oqrtwef,Melanie Moreno,start fuck shit otherwise self sabotaging exac...,7,1
7,oqrtwef,Sincere Rhea,[ISLANDER] fuck boy feel got wait start fuck,7,1
8,oqs621i,Melanie Moreno,agree [ISLANDER] tried get lick back make sens...,7,1
9,oqs621i,Sincere Rhea,go tit tat without hurting feelings maybe [ISL...,7,1

In [134]:
con.close()

### Proportions

In [135]:
con = duckdb.connect("../data/love_island_reddit.duckdb")

# Calculate counts and proportions in one go
proportion_df = con.execute("""
    SELECT 
        target_islander,
        COUNT(*) as mention_count,
        ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) as proportion_pct
    FROM islander_windows
    GROUP BY target_islander
    ORDER BY mention_count DESC
""").df()

con.close()

In [136]:
proportion_df

          target_islander  mention_count  proportion_pct
0          Melanie Moreno          26571           10.87
1            Sincere Rhea          25432           10.41
2         Mackenzie Annis          22263            9.11
3          Kuman Chandler          20156            8.25
4      Zacharias Georgiou          18771            7.68
5            Aniya Harvey          18590            7.61
6   Bryce Alakai Dettloff          14756            6.04
7             Kayda Bosse          14139            5.79
8           Trinity Tatum          12969            5.31
9             Corbin Mims          11149            4.56
10         Jennifer Terry           6202            2.54
11       Carl Lee Schmidt           6194            2.53
12         Caleb McDaniel           5563            2.28
13               Sol Dean           5282            2.16
14           Tierra Davis           5101            2.09
15            Dylan Wrona           4715            1.93
16           Beatriz Hatz           4671            1.91
17    Gabriel Vasconcelos           4587            1.88
18        Parmida Keshani           4496            1.84
19          Gal Tshnieder           3107            1.27
20            Sean Reifel           2419            0.99
21  Amora Cacheé Robinson           2294            0.94
22         Alannah Keyser           1287            0.53
23       Jaiden Bacciocco           1017            0.42
24       Corey Sawyer Jr.            974            0.40
25        Sherleaz Eugene            546            0.22
26           Chaten Nehra            514            0.21
27          Ronnie Gunter            404            0.17
28            Kyle Greene             62            0.03
29        Chandlar Wilson             38            0.02
30            Keyon Harry             24            0.01
31             Tino Ellis             22            0.01
32      Ryan Ten Hulscher             18            0.01
33            Trae Taylor             18            0.01

In [137]:
con = duckdb.connect("../data/love_island_reddit.duckdb")

con.execute("""
ALTER TABLE islander_windows
ADD COLUMN IF NOT EXISTS created_at DATE
""")

con.execute("""
ALTER TABLE islander_windows
ADD COLUMN IF NOT EXISTS keep_analysis VARCHAR
""")

In [138]:
con.execute("""
UPDATE islander_windows AS w
SET
    created_at = CAST(c.created_at AS DATE),
    keep_analysis = c.keep_analysis
FROM comments AS c
WHERE w.comment_id = c.id
""")

In [139]:
con.execute("""
SELECT *
FROM islander_windows
LIMIT 5
""").df()

,comment_id,target_islander,window_text,episode,entrance_episode,created_at,keep_analysis
0,oqrjrnv,Bryce Alakai Dettloff,[ISLANDER] bragged guys kind nice girl [emoji_...,7,1,2026-06-09,Y
1,oqrv3z0,Trinity Tatum,yeah enjoy interactions feel way [ISLANDER] ta...,7,1,2026-06-09,Y
2,oqrhf82,Bryce Alakai Dettloff,glad [ISLANDER] trin involved mess hope ages well,7,1,2026-06-09,Y
3,oqrkife,Gabriel Vasconcelos,[ISLANDER] gross wants fuck,7,3,2026-06-09,Y
4,oqrrs6p,Melanie Moreno,[ISLANDER] double dipping last episode offende...,7,1,2026-06-09,Y

In [140]:
con.close()

## Create Target Windows - Lightly Cleaned Text
1. Load `body_clean_light` from comments.
2. Reuse your `islander_map` to find target mentions.
3. Extract context around each mention while preserving punctuation, capitalization, negation, and emojis.
4. Apply your existing study-period and entrance-episode filters.
5. Save to `islander_sentiment_windows` in DuckDB.

This will be used for sentiment analysis in notebook 5. We will use the prior existing `islander_windows` table for notebook 4.

In [141]:
import hashlib
import json
import re

import duckdb
import pandas as pd

CONTEXT_WORDS = 15

# Match longer aliases first, including multiword names.
def make_name_pattern(names):
    aliases = sorted(set(names), key=len, reverse=True)
    patterns = [
        r"\s+".join(re.escape(part) for part in alias.split())
        for alias in aliases
    ]
    return re.compile(
        r"(?<!\w)(?:" + "|".join(patterns) + r")(?!\w)",
        flags=re.IGNORECASE,
    )

target_patterns = {
    islander: make_name_pattern([islander, *aliases])
    for islander, aliases in islander_map.items()
}

all_name_pattern = make_name_pattern([
    name
    for islander, aliases in islander_map.items()
    for name in [islander, *aliases]
])

metadata = pd.read_csv("../data/metadata/islander_metadata.csv")
assert metadata["islander"].is_unique

entrance_lookup = metadata.set_index("islander")["entrance_episode"]

missing = set(islander_map) - set(entrance_lookup.dropna().index)
if missing:
    raise ValueError(f"Missing entrance episodes: {sorted(missing)}")

with duckdb.connect("../data/love_island_reddit.duckdb") as con:
    comments_light = con.execute("""
        SELECT
            id AS comment_id,
            episode,
            created_at,
            body_clean_light
        FROM comments
        WHERE keep_analysis = 'Y'
          AND episode IS NOT NULL
          AND body_clean_light IS NOT NULL
          AND TRIM(body_clean_light) <> ''
        ORDER BY episode, id
    """).df()

# Prevent duplicate source rows from multiplying target windows.
assert comments_light["comment_id"].notna().all()
assert comments_light["comment_id"].is_unique

In [142]:
from bisect import bisect_left, bisect_right

rows = []

for comment in comments_light.itertuples(index=False):
    text = comment.body_clean_light

    words = list(re.finditer(r"\S+", text))
    starts = [word.start() for word in words]
    ends = [word.end() for word in words]

    for islander, pattern in target_patterns.items():
        entrance_episode = int(entrance_lookup[islander])

        if comment.episode < entrance_episode:
            continue

        for mention in pattern.finditer(text):
            first_word = bisect_right(ends, mention.start())
            last_word = bisect_left(starts, mention.end()) - 1

            left = max(0, first_word - CONTEXT_WORDS)
            right = min(len(words), last_word + CONTEXT_WORDS + 1)

            window_start = starts[left]
            window_end = ends[right - 1]
            window_text = text[window_start:window_end]

            # Preserve your name-masking approach in a separate column.
            # The original light slice remains available unchanged.
            masked_text = all_name_pattern.sub("person", window_text)

            identity = [
                str(comment.comment_id),
                islander,
                mention.start(),
                mention.end(),
                window_start,
                window_end,
                window_text,
            ]
            window_id = hashlib.sha256(
                json.dumps(identity, ensure_ascii=False).encode("utf-8")
            ).hexdigest()

            rows.append({
                "window_id": window_id,
                "comment_id": comment.comment_id,
                "target_islander": islander,
                "episode": comment.episode,
                "entrance_episode": entrance_episode,
                "created_at": comment.created_at,
                "keep_analysis": "Y",
                "matched_alias": mention.group(),
                "mention_start": mention.start(),
                "mention_end": mention.end(),
                "window_start": window_start,
                "window_end": window_end,
                "window_text": window_text,
                "model_text": masked_text,
                "text_source": "body_clean_light",
                "context_words": CONTEXT_WORDS,
            })

sentiment_windows = pd.DataFrame(rows)

assert not sentiment_windows.empty
assert sentiment_windows["window_id"].is_unique
assert sentiment_windows["window_text"].str.strip().ne("").all()
assert (
    sentiment_windows["episode"]
    >= sentiment_windows["entrance_episode"]
).all()

print(
    f"Built {len(sentiment_windows):,} sentiment windows "
    f"for {sentiment_windows['target_islander'].nunique()} islanders."
)

sentiment_windows[
    ["target_islander", "episode", "window_text", "model_text"]
].head(10)

Built 244,397 sentiment windows for 34 islanders.

,target_islander,episode,window_text,model_text
0,Aniya Harvey,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...
1,Beatriz Hatz,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...
2,Bryce Alakai Dettloff,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...
3,Kuman Chandler,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...
4,Mackenzie Annis,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...
5,Melanie Moreno,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...
6,Sean Reifel,1,predict aniya & kc trinity & bryce melanie & s...,predict person & person person & person person...
7,Sincere Rhea,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...
8,Trinity Tatum,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...
9,Zacharias Georgiou,1,i predict aniya & kc trinity & bryce melanie &...,i predict person & person person & person pers...

### Proportions

In [143]:
sentiment_proportions = (
    sentiment_windows
    .groupby("target_islander")
    .size()
    .reset_index(name="mention_count")
    .sort_values("mention_count", ascending=False)
    .reset_index(drop=True)
)

sentiment_proportions["proportion_pct"] = (
    sentiment_proportions["mention_count"]
    / sentiment_proportions["mention_count"].sum()
    * 100
).round(2)

sentiment_proportions

          target_islander  mention_count  proportion_pct
0          Melanie Moreno          26572           10.87
1            Sincere Rhea          25434           10.41
2         Mackenzie Annis          22268            9.11
3          Kuman Chandler          20172            8.25
4      Zacharias Georgiou          18773            7.68
5            Aniya Harvey          18602            7.61
6   Bryce Alakai Dettloff          14757            6.04
7             Kayda Bosse          14139            5.79
8           Trinity Tatum          12969            5.31
9             Corbin Mims          11149            4.56
10         Jennifer Terry           6202            2.54
11       Carl Lee Schmidt           6196            2.54
12         Caleb McDaniel           5563            2.28
13               Sol Dean           5283            2.16
14           Tierra Davis           5104            2.09
15            Dylan Wrona           4715            1.93
16           Beatriz Hatz           4671            1.91
17    Gabriel Vasconcelos           4587            1.88
18        Parmida Keshani           4496            1.84
19          Gal Tshnieder           3107            1.27
20            Sean Reifel           2419            0.99
21  Amora Cacheé Robinson           2294            0.94
22         Alannah Keyser           1287            0.53
23       Jaiden Bacciocco           1017            0.42
24       Corey Sawyer Jr.            974            0.40
25        Sherleaz Eugene            546            0.22
26           Chaten Nehra            515            0.21
27          Ronnie Gunter            404            0.17
28            Kyle Greene             62            0.03
29        Chandlar Wilson             38            0.02
30            Keyon Harry             24            0.01
31             Tino Ellis             22            0.01
32      Ryan Ten Hulscher             18            0.01
33            Trae Taylor             18            0.01

### Save sentiment tables to DuckDB
Rerunning refreshes the two sentiment tables. The heavy `islander_windows` table is preserved.

In [144]:
assert sentiment_windows["window_id"].is_unique
assert sentiment_proportions["mention_count"].sum() == len(sentiment_windows)

with duckdb.connect("../data/love_island_reddit.duckdb") as con:
    con.register("sentiment_windows_export", sentiment_windows)
    con.register("sentiment_proportions_export", sentiment_proportions)
    con.execute("BEGIN TRANSACTION")
    try:
        con.execute("""
            CREATE OR REPLACE TABLE islander_sentiment_windows AS
            SELECT * FROM sentiment_windows_export
        """)
        con.execute("""
            CREATE OR REPLACE TABLE islander_sentiment_proportions AS
            SELECT * FROM sentiment_proportions_export
        """)
        saved_count, unique_ids = con.execute("""
            SELECT COUNT(*), COUNT(DISTINCT window_id)
            FROM islander_sentiment_windows
        """).fetchone()
        assert saved_count == unique_ids == len(sentiment_windows)
        con.execute("COMMIT")
    except Exception:
        con.execute("ROLLBACK")
        raise

print(f"Saved {saved_count:,} rows to islander_sentiment_windows.")
print(f"Saved {len(sentiment_proportions)} rows to islander_sentiment_proportions.")

Saved 244,397 rows to islander_sentiment_windows.
Saved 34 rows to islander_sentiment_proportions.

# Data Validation

Check sentiment coverage among eligible Season 8 light-text comments. A covered comment produced at least one target window after the entrance-episode filter. Uncovered comments may omit known names, discuss logistics, or mention a contestant before entrance.

In [145]:
covered = comments_light["comment_id"].isin(sentiment_windows["comment_id"])
stats = pd.DataFrame([{
    "eligible_light_comments": len(comments_light),
    "comments_with_valid_target_windows": int(covered.sum()),
    "comments_without_valid_target_windows": int((~covered).sum()),
    "sentiment_windows": len(sentiment_windows),
}])
stats

,eligible_light_comments,comments_with_valid_target_windows,comments_without_valid_target_windows,sentiment_windows
0,203749,131718,72031,244397

In [146]:
orphaned_comments = comments_light.loc[
    ~covered, ["comment_id", "episode", "body_clean_light"]
].head(50)

In [147]:
orphaned_comments.head(20)

   comment_id  episode                                   body_clean_light
0     opf7e9q        1  ## 💛 WARNING: THIS IS THE SPOILER LIVE VIEWING...
1     opf7m08        1                                We are SO back!! ♥️
2     opf7p32        1           i hope there will be no delays tonight 😅
3     opf7p7h        1                                       i am ready 😈
4     opf7px7        1  Who is refreshing the episodes tab on peacock ...
5     opf7t6k        1                              ![img](524h4ethoy4h1)
6     opf7thr        1                   I am ready ![img](ixfvirihoy4h1)
7     opf7w7k        1                              ![img](aajml8uioy4h1)
8     opf7y4i        1  ![img](1bauwm3koy4h1) I am sat you all let us ...
9     opf80s7        1  Ohhhhhh yesss Edit to add : TONIGHT *insert go...
10    opf81wz        1  If you need a peacock account to watch use thi...
11    opf82d7        1                            I am so READY LET US GO
12    opf8jo4        1  Hiiiii besties. Excited to spend another summe...
13    opf8q2h        1                                When does it start?
14    opf8ssy        1  please let it come up at 8:30. I missed love i...
15    opf8wya        1  Remember last year when the episode was delaye...
16    opf8xbs        1         Please do not be hella late like last year
17    opf91eb        1  My poor unsuspecting husband has no idea that ...
18    opf92e7        1            let us gooooo, i hope it is up early!!!
19    opf92p1        1                                I am sooooo excited

In [148]:
from datetime import datetime
print(datetime.now())

2026-10-21 14:15:20.844352